In [246]:
import numpy as np
import pandas as pd
import random

### Pré-processando os dados

In [ ]:
train_df = pd.read_csv('train.csv')
x = train_df[['x1', 'x2', 'x3']].to_numpy()
d = train_df['d'].to_numpy()
d = d.reshape(d.shape[0], 1).transpose()
x = x.transpose()
x = np.insert(x, 0, -1 * np.ones(x.shape[1]), axis=0)
x.shape

[[-0.6508  0.1097  4.0009]
 [-1.4492  0.8896  4.4005]
 [ 2.085   0.6876 12.071 ]
 [ 0.2626  1.1476  7.7985]
 [ 0.6418  1.0234  7.0427]
 [ 0.2569  0.673   8.3265]
 [ 1.1155  0.6043  7.4446]
 [ 0.0914  0.3399  7.0677]
 [ 0.0121  0.5256  4.6316]
 [-0.0429  0.466   5.4323]
 [ 0.434   0.687   8.2287]
 [ 0.2735  1.0287  7.1934]
 [ 0.4839  0.4851  7.485 ]
 [ 0.4089 -0.1267  5.5019]
 [ 1.4391  0.1614  8.5843]
 [-0.9115 -0.1973  2.1962]
 [ 0.3654  1.0475  7.4858]
 [ 0.2144  0.7515  7.1699]
 [ 0.2013  1.0014  6.5489]
 [ 0.6483  0.2183  5.8991]
 [-0.1147  0.2242  7.2435]
 [-0.797   0.8795  3.8762]
 [-1.0625  0.6366  2.4707]
 [ 0.5307  0.1285  5.6883]
 [-1.22    0.7777  1.7252]
 [ 0.3957  0.1076  5.6623]
 [-0.1013  0.5989  7.1812]
 [ 2.4482  0.9455 11.2095]
 [ 2.0149  0.6192 10.9263]
 [ 0.2012  0.2611  5.4631]]


(4, 30)

### Vetor Peso

In [248]:
w = np.ones(x.shape[0]) * [random.random() for _ in range(x.shape[0])]
w = np.reshape(w, (w.shape[0], 1))
w.shape

(4, 1)

### Hiperparâmetros

In [249]:
args = {
    'lr': 0.1
}

In [250]:
w

array([[0.25816007],
       [0.73005551],
       [0.55898572],
       [0.85485223]])

### Treinamento

In [251]:
num_epochs = 0
weight_results = []
while True:
    error = False
    for i in range(d.shape[1]):
        u = np.dot(w.T, x[:, i]) # seleciona-se a coluna, representativa de cada amostra
        y_pred = np.sign(u)

        if y_pred[0] != d[:, i][0]:
            w += args['lr'] * (d[:,i] - y_pred[0]) * x[:, i].reshape(-1, 1) # para que o x seja vetor coluna também, para a soma funcionar
            error = True
    num_epochs += 1
    weight_results.append(w.copy())
    if not error:
        break
print(num_epochs)
print(weight_results)

406
[array([[0.05816007],
       [0.62687551],
       [1.35816572],
       [0.16801223]]), array([[-0.14183993],
       [ 0.70781551],
       [ 2.02604572],
       [-0.40926777]]), array([[-0.54183993],
       [ 0.79117551],
       [ 2.64724572],
       [ 0.70429223]]), array([[-0.34183993],
       [ 1.02801551],
       [ 2.81368572],
       [-1.37422777]]), array([[-0.74183993],
       [ 1.18271551],
       [ 3.46938572],
       [-0.55900777]]), array([[-0.94183993],
       [ 1.23445551],
       [ 4.02330572],
       [-0.26072777]]), array([[-0.94183993],
       [ 1.85103551],
       [ 4.28100572],
       [-0.73340777]]), array([[-1.14183993],
       [ 1.32545551],
       [ 4.63056572],
       [-1.77488777]]), array([[-1.54183993],
       [ 0.99725551],
       [ 5.22112572],
       [-1.76012777]]), array([[-1.94183993],
       [ 1.31809551],
       [ 5.82488572],
       [-0.27870777]]), array([[-1.94183993],
       [ 2.15007551],
       [ 5.96436572],
       [ 0.04621223]]), array([[-

In [252]:
w

array([[-30.54183993],
       [ 15.63141551],
       [ 24.58568572],
       [ -7.28970777]])

In [253]:
y_pred.shape

(1,)

### Fase de Operação

In [254]:
for i in range(d.shape[1]):
    u = w.T @ x # operador matricial do numpy além de np.dot
    y_pred = np.sign(u)
    print(f"Amostra {i+1} pertencente à classe {'C1' if y_pred[0, i] < 0 else 'C2'}.")



Amostra 1 pertencente à classe C1.
Amostra 2 pertencente à classe C1.
Amostra 3 pertencente à classe C1.
Amostra 4 pertencente à classe C2.
Amostra 5 pertencente à classe C2.
Amostra 6 pertencente à classe C1.
Amostra 7 pertencente à classe C2.
Amostra 8 pertencente à classe C1.
Amostra 9 pertencente à classe C2.
Amostra 10 pertencente à classe C2.
Amostra 11 pertencente à classe C1.
Amostra 12 pertencente à classe C2.
Amostra 13 pertencente à classe C1.
Amostra 14 pertencente à classe C1.
Amostra 15 pertencente à classe C1.
Amostra 16 pertencente à classe C1.
Amostra 17 pertencente à classe C2.
Amostra 18 pertencente à classe C2.
Amostra 19 pertencente à classe C2.
Amostra 20 pertencente à classe C2.
Amostra 21 pertencente à classe C1.
Amostra 22 pertencente à classe C2.
Amostra 23 pertencente à classe C2.
Amostra 24 pertencente à classe C2.
Amostra 25 pertencente à classe C2.
Amostra 26 pertencente à classe C1.
Amostra 27 pertencente à classe C1.
Amostra 28 pertencente à classe C2.
A

In [255]:
u = w.T @ x
y_pred = np.sign(u).ravel()

c1 = list(filter(lambda x: x[1] < 0, enumerate(y_pred)))
c2 = list(filter(lambda x: x[1] > 0, enumerate(y_pred)))
print("Amostras pertencentes à classe C1:", *list(map(lambda x: x[0]+1, c1)))
print(f"Amostras pertencentes à classe C2:", *list(map(lambda x: x[0]+1, c2)))


Amostras pertencentes à classe C1: 1 2 3 6 8 11 13 14 15 16 21 26 27 29
Amostras pertencentes à classe C2: 4 5 7 9 10 12 17 18 19 20 22 23 24 25 28 30
